events {
    worker_connections 1024;
}

http {
    upstream backend-dev {
        server backend-dev:8082;
    }

    server {
        listen 80;

        location /api {
            proxy_pass http://backend-dev;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /swagger-ui {
            proxy_pass http://backend-dev;
            proxy_set_header Host $host;
        }

        location /api-docs {
            proxy_pass http://backend-dev;
            proxy_set_header Host $host;
        }
    }
}