server.port=8082

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Swagger ACTIVADO
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Logging verbose
logging.level.com.congreso=DEBUG
logging.level.org.springframework.security=DEBUG

# Frontend
app.frontend.url=http://localhost:5173