# Puerto del servidor
server.port=8081

# CORS URL del bucket S3 del frontend
app.cors.allowed-origins=http://congress-frontend.s3-website.us-east-2.amazonaws.com

# Swagger desactivado en produccion
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Logging reducido
logging.level.com.congreso=INFO
logging.level.org.springframework.security=WARN

# Actuator solo health (para healthcheck de Docker)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Frontend URL para emails de invitacion
app.frontend.url=http://congress-frontend.s3-website.us-east-2.amazonaws.com

spring.jackson.time-zone=America/Guatemala